### ISSUE TITLE
Mobile Nav items inherit custom padding for Nav. items background indicator

### ISSUE THREAD

**Issue by webinjection** [elixirgraphics/foundry_issue_tracker#47]
If padding is used for a background indicator, this should be automatically ignored for the mobile version (which should just go to the defaults - say ~ 5-10 px top/bottom that is used for most responsive menus)

![image](https://cloud.githubusercontent.com/assets/25494037/25730154/ba4fed0c-317d-11e7-8d66-b54f0fc8e4d8.png)

**Comment by elixirgraphics** [comment]
Is this in relation to the Navigation Bar stack or the Mega Menu stack?

**Comment by webinjection** [comment]
The standard Nav. Bar stack

**Comment by webinjection** [comment]
Mega Menu doesn't have the same issue as the Nav. Bar stack because Navigation Item heights can be set independently for Mobile / Tablet / Desktop.  

But I think the Nav. Bar stack is built differently? The way I understand it (might be totally off here!) is that the Nav. Bar stack's final item height is determined by the T-B padding setting of an active background?  Whereas in Mega Menu, the active background has no padding setting and its height is determined by the Navigation Items height setting?

![image](https://user-images.githubusercontent.com/25494037/27462370-b9a8a04a-5803-11e7-91dc-ed6a85324eba.png)

**Comment by elixirgraphics** [comment]
Mega Menu doesn't have the problem now because I fixed it in the latest update.  😉 

It too had the same problem. But you are correct they are built differently. Mega Menu provides some refinement options that the normal Nav Bar doesn't offer and probably won't offer due to their differences. I will take a look at the normal Navigation Bar stack and see if I can't fix it up though.

**Comment by elixirgraphics** [comment]
Finally fixed this bug, I think. Sorry it took so long @webinjection. Should be in the next update v1.2.5.4.
